DROP TABLE EMPLOYEE IF EXISTS;

create table EMPLOYEE (
      ID INT,
      FIRST_NAME VARCHAR(50),
      LAST_NAME VARCHAR(50),
      EMAIL VARCHAR(50),
      GENDER VARCHAR(50),
      IP_ADDRESS VARCHAR(20),
      COMPANY_NAME VARCHAR(50),
      JOB_TITLE VARCHAR(50)
);

